import { Inter } from "@next/font/google";
import Head from "next/head";
import Hero from "../../components/Hero";
import Layout from "../../components/Layouts/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rafael Modesto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero />
      </Layout>
    </>
  );
}
